/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package md5cm;

import java.awt.Container;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author meranr
 */
public class Md5Frame extends javax.swing.JFrame {

	/**
	 * Creates new form Md5Frame
	 */
	public Md5Frame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
	 * code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        DirChoose = new javax.swing.JTextField();
        BDirChoose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaMd5 = new javax.swing.JTextArea();
        md5Button = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();

        FileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DirChoose.setText("C:\\Users\\meranr\\Downloads\\cm-10"); // NOI18N
        DirChoose.setToolTipText("");

        BDirChoose.setText("Cartella base");
        BDirChoose.setToolTipText("");
        BDirChoose.setActionCommand("Cartella base...");
        BDirChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDirChooseActionPerformed(evt);
            }
        });

        TextAreaMd5.setColumns(20);
        TextAreaMd5.setRows(5);
        jScrollPane1.setViewportView(TextAreaMd5);

        md5Button.setText("Show Md5");
        md5Button.setActionCommand("ShowMd5");
        md5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md5ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(md5Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DirChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BDirChoose)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DirChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDirChoose)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(md5Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDirChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDirChooseActionPerformed
		// TODO add your handling code here:
		int returnVal = FileChooser.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			DirChoose.setText(FileChooser.getSelectedFile().getPath());
			//This is where a real application would open the file.
		} else {
			DirChoose.setText("");
		}
    }//GEN-LAST:event_BDirChooseActionPerformed

	public class Prefix implements FilenameFilter {

		String pre;

		/**
		 *
		 * @param pre
		 */
		public Prefix(String pre) {
			this.pre = pre;
		}

		public boolean accept(File dir, String name) {
			if (pre.length() > 0) {
				return name.startsWith(pre);
			} else {
				return false;
			}
		}
	}

    private void md5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md5ButtonActionPerformed

		boolean stop = false;
		if(t!= null){
			Logger.getLogger(Md5Frame.class.getName()).log(Level.INFO, "stop");
			t = null;
			stop  = true;
		}

		Runnable runner;
		runner = new Runnable() {
			@Override
			public void run() {
				Thread thisThread = Thread.currentThread();
				
					try {
						Md5Frame.this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
						TextAreaMd5.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
						//Imposto il cursore in stato WAIT

						File theFile = new File(DirChoose.getText());
						String ffiles;
						String patt;
						patt = "";
						boolean isPatt;
						if (!theFile.isDirectory()) {
							patt = theFile.getName();
							ffiles = "Cerco md5 per " + patt + "\n";
						} else {
							ffiles = "Cerco md5 per tutti i file\n";
						}

						isPatt = (patt.length() > 0);

						TextAreaMd5.setText(ffiles);
						File dir;
						if (isPatt) {
							dir = new File(theFile.getParent());
						} else {
							dir = theFile;
						}
						if (dir.isDirectory()) {
							FilenameFilter filtro = new Prefix(patt);
							String[] children;
							if (isPatt) {
								children = dir.list(filtro);
							} else {
								children = dir.list();
							}

							ProgressBar.setValue(0);
							ProgressBar.setIndeterminate(true);
							ProgressBar.setStringPainted(true);
							ffiles += "Esamino " + children.length + " file\n";
							int c = children.length;
							for (int i = 0; i < children.length && t == thisThread; i++) {

								try {
									File f = new File(dir, children[i]);
									if (f.exists() && !f.isDirectory()) {
										ffiles += f.getName() + ":\t" + getMd5Sum(f) + "\n";
										TextAreaMd5.setText(ffiles);
										ProgressBar.setIndeterminate(false);
									}

									ProgressBar.setValue(100 * (i + 1) / c);


								} catch (IOException | NoSuchAlgorithmException ex) {
									Logger.getLogger(Md5Frame.class.getName()).log(Level.SEVERE, null, ex);
								}

							}
						}
						String ending = "Finito";
						if(t != thisThread){
							ending = "Interrotto";
						}
						TextAreaMd5.setText(ffiles + "\n" + ending +"!" );
						md5Button.setText("Show md5");
					}/*catch(InterruptedException e){
					
					} */
					finally {
						Md5Frame.this.setCursor(Cursor.getDefaultCursor());
						TextAreaMd5.setCursor(Cursor.getDefaultCursor());
					}
				}
			
		};
		
		
		if(!stop){
			
			t = new Thread(runner, "Code Executer");
			t.start();
			md5Button.setText("Stop md5");
		}

    }//GEN-LAST:event_md5ButtonActionPerformed

	private String getMd5Sum(File file) throws IOException, NoSuchAlgorithmException {
		// Get an MD5 implementation of MessageDigest

		MessageDigest digest = MessageDigest.getInstance("MD5");
		try (InputStream is = new FileInputStream(file)) {
			byte[] buffer = new byte[8192];
			int read = 0;
			while ((read = is.read(buffer)) >= 0) {
				// pass data read from file to digest for processing

				digest.update(buffer, 0, read);
			}
		} catch (FileNotFoundException e) {
			Logger.getLogger(Md5Frame.class.getName()).log(Level.SEVERE, null, e);
		}

// Get the MD5 sum

		byte[] md5sum = digest.digest();

// (Optionally) convert the MD5 byte array to a hex string

		String md5sumHex = new BigInteger(1, md5sum).toString(16);

		return md5sumHex;

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Md5Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Md5Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Md5Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Md5Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Md5Frame().setVisible(true);
			}
		});
	}
	private volatile Thread t = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDirChoose;
    private javax.swing.JTextField DirChoose;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JTextArea TextAreaMd5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton md5Button;
    // End of variables declaration//GEN-END:variables
}
